# inherit_from: .rubocop_todo.yml
# require:
#   - rubocop-rspec
#   - rubocop-performance

# AllCops:
#   EnabledByDefault: true
#   TargetRubyVersion: 2.5.5
#   Exclude:
#     - 'app/views/**/*'
#     - 'db/**/*'
#     - 'bin/**/*'
#     - 'csv/**/*'
#     - 'slate/**/*'
#     - 'vendor/bundle/**/*'
#     - 'node_modules/**/*'